import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import AxiomProvider from './axiomProvider';
import Sidebar from './components/ui/Sidebar'; // Import your Sidebar component
import { BrowserRouter as Router } from 'react-router-dom';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <Router> */}

      <Providers>
              <AxiomProvider>
              <div className="flex min-h-screen bg-gray-100">
              <Sidebar /> 
              <div className="flex-1 p-8">
                {children}
                </div>
            </div>
              </AxiomProvider>
        </Providers>
        {/* </Router> */}

        </body>
    </html>

  )
}
